resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: github.com_amd-jmacaran
    name: amd-jmacaran/pipelines

trigger:
- develop

jobs:
- job: rocm_smi_lib
  pool:
    vmImage: NV31
  workspace:
    clean: all
  steps:
  - template: templates/steps/preamble.yml@pipelines_repo
  - template: templates/steps/checkout.yml@pipelines_repo
