resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: github.com_amd-jmacaran
    name: amd-jmacaran/pipelines

trigger:
- develop

pool: NV31

jobs:
- job: rocm_smi_lib
  workspace:
    clean: all
  steps:
  - template: templates/steps/preamble.yml@pipelines_repo
  - template: templates/steps/checkout.yml@pipelines_repo

  - script: |
      mkdir -p build
      cd build
      cmake ..
      make -j $(nproc)
      sudo make install
      cmake -DBUILD_TESTS=ON ..
      make -j $(nproc)
      cd tests/rocm_smi_test 
      ./rsmitst --gtest_output=xml:output_psdb.xml
      



    
